// Generated by gencpp from file quadrotor_sim/AddTwoInts.msg
// DO NOT EDIT!


#ifndef QUADROTOR_SIM_MESSAGE_ADDTWOINTS_H
#define QUADROTOR_SIM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <quadrotor_sim/AddTwoIntsRequest.h>
#include <quadrotor_sim/AddTwoIntsResponse.h>


namespace quadrotor_sim
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace quadrotor_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quadrotor_sim::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::quadrotor_sim::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::quadrotor_sim::AddTwoInts > {
  static const char* value()
  {
    return "quadrotor_sim/AddTwoInts";
  }

  static const char* value(const ::quadrotor_sim::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::quadrotor_sim::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::quadrotor_sim::AddTwoInts > 
template<>
struct MD5Sum< ::quadrotor_sim::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_sim::AddTwoInts >::value();
  }
  static const char* value(const ::quadrotor_sim::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_sim::AddTwoIntsRequest> should match 
// service_traits::DataType< ::quadrotor_sim::AddTwoInts > 
template<>
struct DataType< ::quadrotor_sim::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::quadrotor_sim::AddTwoInts >::value();
  }
  static const char* value(const ::quadrotor_sim::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quadrotor_sim::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::quadrotor_sim::AddTwoInts > 
template<>
struct MD5Sum< ::quadrotor_sim::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_sim::AddTwoInts >::value();
  }
  static const char* value(const ::quadrotor_sim::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_sim::AddTwoIntsResponse> should match 
// service_traits::DataType< ::quadrotor_sim::AddTwoInts > 
template<>
struct DataType< ::quadrotor_sim::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::quadrotor_sim::AddTwoInts >::value();
  }
  static const char* value(const ::quadrotor_sim::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUADROTOR_SIM_MESSAGE_ADDTWOINTS_H
