// Generated by gencpp from file quadrotor_sim/mc_plan.msg
// DO NOT EDIT!


#ifndef QUADROTOR_SIM_MESSAGE_MC_PLAN_H
#define QUADROTOR_SIM_MESSAGE_MC_PLAN_H

#include <ros/service_traits.h>


#include <quadrotor_sim/mc_planRequest.h>
#include <quadrotor_sim/mc_planResponse.h>


namespace quadrotor_sim
{

struct mc_plan
{

typedef mc_planRequest Request;
typedef mc_planResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mc_plan
} // namespace quadrotor_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quadrotor_sim::mc_plan > {
  static const char* value()
  {
    return "7bebb743b8230fc9c43aee4ab5473ce7";
  }

  static const char* value(const ::quadrotor_sim::mc_plan&) { return value(); }
};

template<>
struct DataType< ::quadrotor_sim::mc_plan > {
  static const char* value()
  {
    return "quadrotor_sim/mc_plan";
  }

  static const char* value(const ::quadrotor_sim::mc_plan&) { return value(); }
};


// service_traits::MD5Sum< ::quadrotor_sim::mc_planRequest> should match 
// service_traits::MD5Sum< ::quadrotor_sim::mc_plan > 
template<>
struct MD5Sum< ::quadrotor_sim::mc_planRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_sim::mc_plan >::value();
  }
  static const char* value(const ::quadrotor_sim::mc_planRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_sim::mc_planRequest> should match 
// service_traits::DataType< ::quadrotor_sim::mc_plan > 
template<>
struct DataType< ::quadrotor_sim::mc_planRequest>
{
  static const char* value()
  {
    return DataType< ::quadrotor_sim::mc_plan >::value();
  }
  static const char* value(const ::quadrotor_sim::mc_planRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quadrotor_sim::mc_planResponse> should match 
// service_traits::MD5Sum< ::quadrotor_sim::mc_plan > 
template<>
struct MD5Sum< ::quadrotor_sim::mc_planResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_sim::mc_plan >::value();
  }
  static const char* value(const ::quadrotor_sim::mc_planResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_sim::mc_planResponse> should match 
// service_traits::DataType< ::quadrotor_sim::mc_plan > 
template<>
struct DataType< ::quadrotor_sim::mc_planResponse>
{
  static const char* value()
  {
    return DataType< ::quadrotor_sim::mc_plan >::value();
  }
  static const char* value(const ::quadrotor_sim::mc_planResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUADROTOR_SIM_MESSAGE_MC_PLAN_H
