// Generated by gencpp from file quadrotor_sim/move_quad.msg
// DO NOT EDIT!


#ifndef QUADROTOR_SIM_MESSAGE_MOVE_QUAD_H
#define QUADROTOR_SIM_MESSAGE_MOVE_QUAD_H

#include <ros/service_traits.h>


#include <quadrotor_sim/move_quadRequest.h>
#include <quadrotor_sim/move_quadResponse.h>


namespace quadrotor_sim
{

struct move_quad
{

typedef move_quadRequest Request;
typedef move_quadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_quad
} // namespace quadrotor_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quadrotor_sim::move_quad > {
  static const char* value()
  {
    return "30f567500cb1fdfeac7274b9d9e7eaf0";
  }

  static const char* value(const ::quadrotor_sim::move_quad&) { return value(); }
};

template<>
struct DataType< ::quadrotor_sim::move_quad > {
  static const char* value()
  {
    return "quadrotor_sim/move_quad";
  }

  static const char* value(const ::quadrotor_sim::move_quad&) { return value(); }
};


// service_traits::MD5Sum< ::quadrotor_sim::move_quadRequest> should match 
// service_traits::MD5Sum< ::quadrotor_sim::move_quad > 
template<>
struct MD5Sum< ::quadrotor_sim::move_quadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_sim::move_quad >::value();
  }
  static const char* value(const ::quadrotor_sim::move_quadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_sim::move_quadRequest> should match 
// service_traits::DataType< ::quadrotor_sim::move_quad > 
template<>
struct DataType< ::quadrotor_sim::move_quadRequest>
{
  static const char* value()
  {
    return DataType< ::quadrotor_sim::move_quad >::value();
  }
  static const char* value(const ::quadrotor_sim::move_quadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quadrotor_sim::move_quadResponse> should match 
// service_traits::MD5Sum< ::quadrotor_sim::move_quad > 
template<>
struct MD5Sum< ::quadrotor_sim::move_quadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quadrotor_sim::move_quad >::value();
  }
  static const char* value(const ::quadrotor_sim::move_quadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quadrotor_sim::move_quadResponse> should match 
// service_traits::DataType< ::quadrotor_sim::move_quad > 
template<>
struct DataType< ::quadrotor_sim::move_quadResponse>
{
  static const char* value()
  {
    return DataType< ::quadrotor_sim::move_quad >::value();
  }
  static const char* value(const ::quadrotor_sim::move_quadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUADROTOR_SIM_MESSAGE_MOVE_QUAD_H
