# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_sim/mc_planRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy
import nav_msgs.msg
import std_msgs.msg

class mc_planRequest(genpy.Message):
  _md5sum = "bb975d1ef6b37dd9003c880e25194ca5"
  _type = "quadrotor_sim/mc_planRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose currentPose
nav_msgs/OccupancyGrid ProjectedGrid

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: nav_msgs/OccupancyGrid
# This represents a 2-D grid map, in which each cell represents the probability of
# occupancy.

Header header 

#MetaData for the map
MapMetaData info

# The map data, in row-major order, starting with (0,0).  Occupancy
# probabilities are in the range [0,100].  Unknown is -1.
int8[] data

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: nav_msgs/MapMetaData
# This hold basic information about the characterists of the OccupancyGrid

# The time at which the map was loaded
time map_load_time
# The map resolution [m/cell]
float32 resolution
# Map width [cells]
uint32 width
# Map height [cells]
uint32 height
# The origin of the map [m, m, rad].  This is the real-world pose of the
# cell (0,0) in the map.
geometry_msgs/Pose origin"""
  __slots__ = ['currentPose','ProjectedGrid']
  _slot_types = ['geometry_msgs/Pose','nav_msgs/OccupancyGrid']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       currentPose,ProjectedGrid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mc_planRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.currentPose is None:
        self.currentPose = geometry_msgs.msg.Pose()
      if self.ProjectedGrid is None:
        self.ProjectedGrid = nav_msgs.msg.OccupancyGrid()
    else:
      self.currentPose = geometry_msgs.msg.Pose()
      self.ProjectedGrid = nav_msgs.msg.OccupancyGrid()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.currentPose.position.x, _x.currentPose.position.y, _x.currentPose.position.z, _x.currentPose.orientation.x, _x.currentPose.orientation.y, _x.currentPose.orientation.z, _x.currentPose.orientation.w, _x.ProjectedGrid.header.seq, _x.ProjectedGrid.header.stamp.secs, _x.ProjectedGrid.header.stamp.nsecs))
      _x = self.ProjectedGrid.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2If2I7d().pack(_x.ProjectedGrid.info.map_load_time.secs, _x.ProjectedGrid.info.map_load_time.nsecs, _x.ProjectedGrid.info.resolution, _x.ProjectedGrid.info.width, _x.ProjectedGrid.info.height, _x.ProjectedGrid.info.origin.position.x, _x.ProjectedGrid.info.origin.position.y, _x.ProjectedGrid.info.origin.position.z, _x.ProjectedGrid.info.origin.orientation.x, _x.ProjectedGrid.info.origin.orientation.y, _x.ProjectedGrid.info.origin.orientation.z, _x.ProjectedGrid.info.origin.orientation.w))
      length = len(self.ProjectedGrid.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.pack(pattern, *self.ProjectedGrid.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.currentPose is None:
        self.currentPose = geometry_msgs.msg.Pose()
      if self.ProjectedGrid is None:
        self.ProjectedGrid = nav_msgs.msg.OccupancyGrid()
      end = 0
      _x = self
      start = end
      end += 68
      (_x.currentPose.position.x, _x.currentPose.position.y, _x.currentPose.position.z, _x.currentPose.orientation.x, _x.currentPose.orientation.y, _x.currentPose.orientation.z, _x.currentPose.orientation.w, _x.ProjectedGrid.header.seq, _x.ProjectedGrid.header.stamp.secs, _x.ProjectedGrid.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ProjectedGrid.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ProjectedGrid.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.ProjectedGrid.info.map_load_time.secs, _x.ProjectedGrid.info.map_load_time.nsecs, _x.ProjectedGrid.info.resolution, _x.ProjectedGrid.info.width, _x.ProjectedGrid.info.height, _x.ProjectedGrid.info.origin.position.x, _x.ProjectedGrid.info.origin.position.y, _x.ProjectedGrid.info.origin.position.z, _x.ProjectedGrid.info.origin.orientation.x, _x.ProjectedGrid.info.origin.orientation.y, _x.ProjectedGrid.info.origin.orientation.z, _x.ProjectedGrid.info.origin.orientation.w,) = _get_struct_2If2I7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      end += struct.calcsize(pattern)
      self.ProjectedGrid.data = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.currentPose.position.x, _x.currentPose.position.y, _x.currentPose.position.z, _x.currentPose.orientation.x, _x.currentPose.orientation.y, _x.currentPose.orientation.z, _x.currentPose.orientation.w, _x.ProjectedGrid.header.seq, _x.ProjectedGrid.header.stamp.secs, _x.ProjectedGrid.header.stamp.nsecs))
      _x = self.ProjectedGrid.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2If2I7d().pack(_x.ProjectedGrid.info.map_load_time.secs, _x.ProjectedGrid.info.map_load_time.nsecs, _x.ProjectedGrid.info.resolution, _x.ProjectedGrid.info.width, _x.ProjectedGrid.info.height, _x.ProjectedGrid.info.origin.position.x, _x.ProjectedGrid.info.origin.position.y, _x.ProjectedGrid.info.origin.position.z, _x.ProjectedGrid.info.origin.orientation.x, _x.ProjectedGrid.info.origin.orientation.y, _x.ProjectedGrid.info.origin.orientation.z, _x.ProjectedGrid.info.origin.orientation.w))
      length = len(self.ProjectedGrid.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.ProjectedGrid.data.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.currentPose is None:
        self.currentPose = geometry_msgs.msg.Pose()
      if self.ProjectedGrid is None:
        self.ProjectedGrid = nav_msgs.msg.OccupancyGrid()
      end = 0
      _x = self
      start = end
      end += 68
      (_x.currentPose.position.x, _x.currentPose.position.y, _x.currentPose.position.z, _x.currentPose.orientation.x, _x.currentPose.orientation.y, _x.currentPose.orientation.z, _x.currentPose.orientation.w, _x.ProjectedGrid.header.seq, _x.ProjectedGrid.header.stamp.secs, _x.ProjectedGrid.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ProjectedGrid.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ProjectedGrid.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.ProjectedGrid.info.map_load_time.secs, _x.ProjectedGrid.info.map_load_time.nsecs, _x.ProjectedGrid.info.resolution, _x.ProjectedGrid.info.width, _x.ProjectedGrid.info.height, _x.ProjectedGrid.info.origin.position.x, _x.ProjectedGrid.info.origin.position.y, _x.ProjectedGrid.info.origin.position.z, _x.ProjectedGrid.info.origin.orientation.x, _x.ProjectedGrid.info.origin.orientation.y, _x.ProjectedGrid.info.origin.orientation.z, _x.ProjectedGrid.info.origin.orientation.w,) = _get_struct_2If2I7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      end += struct.calcsize(pattern)
      self.ProjectedGrid.data = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
_struct_2If2I7d = None
def _get_struct_2If2I7d():
    global _struct_2If2I7d
    if _struct_2If2I7d is None:
        _struct_2If2I7d = struct.Struct("<2If2I7d")
    return _struct_2If2I7d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_sim/mc_planResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class mc_planResponse(genpy.Message):
  _md5sum = "43874bb3f8ebc78572ab5e24194fe094"
  _type = "quadrotor_sim/mc_planResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose nextPose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['nextPose']
  _slot_types = ['geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nextPose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mc_planResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.nextPose is None:
        self.nextPose = geometry_msgs.msg.Pose()
    else:
      self.nextPose = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.nextPose.position.x, _x.nextPose.position.y, _x.nextPose.position.z, _x.nextPose.orientation.x, _x.nextPose.orientation.y, _x.nextPose.orientation.z, _x.nextPose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.nextPose is None:
        self.nextPose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.nextPose.position.x, _x.nextPose.position.y, _x.nextPose.position.z, _x.nextPose.orientation.x, _x.nextPose.orientation.y, _x.nextPose.orientation.z, _x.nextPose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.nextPose.position.x, _x.nextPose.position.y, _x.nextPose.position.z, _x.nextPose.orientation.x, _x.nextPose.orientation.y, _x.nextPose.orientation.z, _x.nextPose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.nextPose is None:
        self.nextPose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.nextPose.position.x, _x.nextPose.position.y, _x.nextPose.position.z, _x.nextPose.orientation.x, _x.nextPose.orientation.y, _x.nextPose.orientation.z, _x.nextPose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
class mc_plan(object):
  _type          = 'quadrotor_sim/mc_plan'
  _md5sum = '7bebb743b8230fc9c43aee4ab5473ce7'
  _request_class  = mc_planRequest
  _response_class = mc_planResponse
